# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_web_image_batch_downloader.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("PMingLiU")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("PMingLiU")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.pushButton_SetOutDir = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SetOutDir.sizePolicy().hasHeightForWidth())
        self.pushButton_SetOutDir.setSizePolicy(sizePolicy)
        self.pushButton_SetOutDir.setObjectName("pushButton_SetOutDir")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_SetOutDir)
        self.plainTextEdit_SaveDir = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_SaveDir.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_SaveDir.setSizePolicy(sizePolicy)
        self.plainTextEdit_SaveDir.setObjectName("plainTextEdit_SaveDir")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_SaveDir)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.pushButton_AddDL = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_AddDL.setObjectName("pushButton_AddDL")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_AddDL)
        self.plainTextEdit_BatchUrl = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_BatchUrl.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_BatchUrl.setSizePolicy(sizePolicy)
        self.plainTextEdit_BatchUrl.setObjectName("plainTextEdit_BatchUrl")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_BatchUrl)
        self.comboBox_batch_urls = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_batch_urls.setObjectName("comboBox_batch_urls")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_batch_urls)
        self.pushButton_RemoveDL = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_RemoveDL.setObjectName("pushButton_RemoveDL")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_RemoveDL)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.formLayout_3)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_Level = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Level.setObjectName("lineEdit_Level")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Level)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_TestDLUrls = QtWidgets.QPushButton(self.frame)
        self.pushButton_TestDLUrls.setObjectName("pushButton_TestDLUrls")
        self.horizontalLayout.addWidget(self.pushButton_TestDLUrls)
        self.pushButton_StartDL = QtWidgets.QPushButton(self.frame)
        self.pushButton_StartDL.setObjectName("pushButton_StartDL")
        self.horizontalLayout.addWidget(self.pushButton_StartDL)
        self.pushButton_ResetDL = QtWidgets.QPushButton(self.frame)
        self.pushButton_ResetDL.setObjectName("pushButton_ResetDL")
        self.horizontalLayout.addWidget(self.pushButton_ResetDL)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.plainTextEdit_Intro = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_Intro.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_Intro.setSizePolicy(sizePolicy)
        self.plainTextEdit_Intro.setMaximumSize(QtCore.QSize(16777215, 130))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_Intro.setFont(font)
        self.plainTextEdit_Intro.setReadOnly(True)
        self.plainTextEdit_Intro.setObjectName("plainTextEdit_Intro")
        self.verticalLayout.addWidget(self.plainTextEdit_Intro)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tableView_Tasks = QtWidgets.QTableView(self.centralwidget)
        self.tableView_Tasks.setEnabled(True)
        self.tableView_Tasks.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_Tasks.setObjectName("tableView_Tasks")
        self.tableView_Tasks.horizontalHeader().setMinimumSectionSize(20)
        self.tableView_Tasks.verticalHeader().setDefaultSectionSize(20)
        self.tableView_Tasks.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_2.addWidget(self.tableView_Tasks)
        self.label_ProcessMessage = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_ProcessMessage.setFont(font)
        self.label_ProcessMessage.setText("")
        self.label_ProcessMessage.setObjectName("label_ProcessMessage")
        self.verticalLayout_2.addWidget(self.label_ProcessMessage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_AddDL.clicked.connect(MainWindow.add_batch_url)
        self.pushButton_RemoveDL.clicked.connect(MainWindow.remove_current_batch_url)
        self.pushButton_SetOutDir.clicked.connect(MainWindow.choose_output_dir)
        self.pushButton_StartDL.clicked.connect(MainWindow.download_imgs)
        self.pushButton_TestDLUrls.clicked.connect(MainWindow.test_urls)
        self.pushButton_ResetDL.clicked.connect(MainWindow.reset_all)
        self.tableView_Tasks.doubleClicked['QModelIndex'].connect(MainWindow.save_img)
        self.plainTextEdit_SaveDir.textChanged['QString'].connect(MainWindow._update_output_paths)
        self.lineEdit_Level.editingFinished.connect(MainWindow._update_output_paths)
        self.plainTextEdit_SaveDir.editingFinished.connect(MainWindow._adjust_root)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "網頁圖片批次下載工具"))
        self.groupBox.setTitle(_translate("MainWindow", "下載設定"))
        self.label.setText(_translate("MainWindow", "批次網址"))
        self.label_2.setText(_translate("MainWindow", "存檔目錄"))
        self.pushButton_SetOutDir.setText(_translate("MainWindow", "選擇目錄"))
        self.pushButton_AddDL.setText(_translate("MainWindow", "新增目標"))
        self.plainTextEdit_BatchUrl.setText(_translate("MainWindow", "http://"))
        self.pushButton_RemoveDL.setText(_translate("MainWindow", "移除目標"))
        self.label_3.setText(_translate("MainWindow", "子目錄層數"))
        self.lineEdit_Level.setText(_translate("MainWindow", "1"))
        self.pushButton_TestDLUrls.setText(_translate("MainWindow", "測試圖片網址狀態"))
        self.pushButton_StartDL.setText(_translate("MainWindow", "開始下載"))
        self.pushButton_ResetDL.setText(_translate("MainWindow", "重置目標"))
        self.plainTextEdit_Intro.setPlainText(_translate("MainWindow", "[批次網址說明]\n"
"以空格切分批次內容的區塊，區塊有以下類別：\n"
"1. 數值：#[#...][L],StartRange,EndRange[,StepValue]]\n"
"從 StartRange 到 EndRange 的值以 StepValue遞增（StartRange 及 EndRange 兩個值皆包含在內）。\n"
"當開頭 # 的個數超過數值長度且最後緊接著 L（paddingLeft）時，會按照 # 的個數做為位數長度於左側補 0 。\n"
"例如 ###L,1,5,2 會得到 001、003、005 。\n"
"2. 列舉：@,Text1[,Text2[,Text3[,...]]]\n"
"將所有可能的文字列出。\n"
"例如 @,aa,bb,cc 就會得到 aa、bb、cc 。\n"
"\n"
"[子目錄層數]\n"
"取用解析網址中檔名前的部分，將各檔案自動存放於存檔目錄中對應名稱的子目錄下。\n"
"\n"
"[滑鼠雙擊網址列表]\n"
"可以直接單獨下載並顯示該圖片。\n"
""))
        self.menu.setTitle(_translate("MainWindow", "功能"))

